version: 2.1

jobs:
  build:
    docker:
      - image: circleci/python:3.9.7
    working_directory: ~/app

    steps:
      - checkout

      - run:
          name: Install Selenium
          command: pip install selenium

      - run:
          name: Install Chromedriver
          command: |
            sudo apt-get update
            sudo apt-get install -y chromium-chromedriver

      - run:
          name: Install Chromedriver
          command: |
            sudo apt-get update
            sudo apt-get install -y unzip
            wget -q https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
            sudo dpkg -i google-chrome-stable_current_amd64.deb
            wget -q https://chromedriver.storage.googleapis.com/$(curl -sS https://chromedriver.storage.googleapis.com/LATEST_RELEASE)/chromedriver_linux64.zip
            unzip chromedriver_linux64.zip
            sudo mv chromedriver /usr/local/bin/
            sudo chmod +x /usr/local/bin/chromedriver